const mongoose = require("mongoose");

const campsiteSchema = new mongoose.Schema({
  url: { type: String, required: true },
  name: { type: String, required: true },
  description: { type: String, required: true },
  id: { type: Number, required: false },
  parkCode: { type: String, required: false },
  latitude: { type: String, required: false },
  longitude: { type: String, required: false },
  latLong: { type: String, required: false },
  audioDescription: { type: String, required: false },
  isPassportStampLocation: { type: String, required: false },
  passportStampLocationDescription: { type: String, required: false },
  passportStampImages: { type: Array, required: false },
  geometryPoiId: { type: String, required: false },
  reservationInfo: { type: String, required: false },
  regulationsurl: { type: String, required: false },
  regulationsOverview: { type: String, required: false },
  amenities: { type: Object, required: false },
  contacts: { type: Object, required: false },
  fees: { type: Array, required: false },
  directionsOverview: { type: String, required: false },
  directionsUrl: { type: String, required: false },
  operatingHours: { type: Array, required: false },
  addresses: { type: Array, required: false },
  images: { type: Array, required: false },
  weatherOverview: { type: String, required: false },
  numberOfSitesReservable: { type: String, required: false },
  numberOfSitesFirstComeFirstServe: { type: String, required: false },
  campsites: { type: Object, required: false },
  accessibility: { type: Object, required: false },
  multimedia: { type: Array, required: false },
  relevanceScore: { type: Number, required: false },
  lastIndexedDate: { type: String, required: false },
  user: { type: mongoose.Schema.Types.ObjectId, required: true, ref: "User" },
});

module.exports = mongoose.model("Campsite", campsiteSchema);
